// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/filter-mdx-strict.cjs
export function getValidMdxModules() {
  return [
    "example-docs/advanced/getting-started.mdx",
    "example-docs/advanced/sub/index.mdx"
  ];
}
