// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/filter-mdx-strict.cjs
export const mdxModules = {
  "/src/docs/example-docs/advanced/getting-started.mdx": () => import("/src/docs/example-docs/advanced/getting-started.mdx"),
  "/src/docs/example-docs/advanced/sub/index.mdx": () => import("/src/docs/example-docs/advanced/sub/index.mdx"),
};
